# Generated by Django 4.2.7 on 2024-06-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_suggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
    ]
